version: '3.8'

services:
  dualshock_publisher:
    image: ghcr.io/action-prediction-lab/dualshock-zmq:latest
    build:
      context: ./dualshock_publisher
      dockerfile: Dockerfile
    env_file:
      - .env
    privileged: true
    volumes:
      - /dev/input:/dev/input
      - ./dualshock_publisher:/app
    ports:
      - "${ZMQ_PORT:-5556}:${ZMQ_PORT:-5556}" # Expose ZeroMQ port
    command: python -u dualshock_publisher.py
    restart: unless-stopped
