version: '3.8'

services:
  dualshock_publisher:
    build:
      context: ./dualshock_publisher
      dockerfile: Dockerfile
    env_file:
      - .env
    privileged: true
    volumes:
      - /dev/input:/dev/input
      - ./dualshock_publisher:/app
    ports:
      - "5556:5556" # Expose ZeroMQ port
    command: python -u dualshock_publisher.py
    restart: unless-stopped
